### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/node-purescript-bin#1]
Thanks for doing this. A little unfortunate it's under the name `purescript` on `npm` as we had been hoping to eventually publish [`purescript-in-purescript`](https://github.com/purescript/purescript-in-purescript) using that name, but nevermind! It might never happen anyway.

I know that technically it's bad practice to do this, but could you unpublish `v1.0.0` and republish it as `v0.6.9` (or whichever version you used) please? Having the `npm` package out of sync with the compiler versions seems like a sure way to confuse people.

I've invited you to a group on `contrib` so you can move the repo over as you offered on purescript/purescript.github.io#20. Could you also grant `garyb` to have access to publish/update the package on `npm` please? (`npm owner add garyb purescript`, I believe).

**Comment by shinnn** [comment]
@garyb Moved the repo and added you to the npm package as an owner.

**Comment by shinnn** [comment]
> Having the `npm` package out of sync with the compiler versions seems like a sure way to confuse people.

Yes, I tried to publish `v0.6.9.3` as you say, but npm cannot parse `v0.6.9.3` as a semver-valid value. Though we can omit the extra digit `.3` and release `v0.6.9` for the present, unfortunately, I found you've released [`v0.6.7`](https://github.com/purescript/purescript/releases/tag/v0.6.7) and [`v0.6.7.1`](https://github.com/purescript/purescript/releases/tag/v0.6.7.1). So, I'm concerned that we cannot sync versions if you release purescript `v0.6.9.4` or something.

**Comment by garyb** [comment]
Thanks!

Yeah, I did wonder about that with the versions - the `0.x.x.x` releases are usually because we made a mistake in the `0.x.x` release and had to get something out quickly to solve it. Perhaps we can wait a little while before releasing `npm` updates to ensure any kinks are worked out. Either that or start releasing `0.x.x-rc1` versions first, which I believe is compatible with semver.

Thoughts @paf31?

**Comment by shinnn** [comment]
> we had been hoping to eventually publish [`purescript-in-purescript`](https://github.com/purescript/purescript-in-purescript) using that name

Oh, great project! purescript-in-purescript is just what I expected. It will be very useful to improve Grunt and gulp plugins. Feel free to ask me to vacate the package name If you ever want to publish purescript-in-purescript as `purescript`.

**Comment by garyb** [comment]
I've downgraded the version to `0.6.9` for now - it's not ideal, but `0.6.9.0` to `0.6.9.2` were broken anyway, so `0.6.9.3` is the "real" `0.6.9`. In the future we'll use `-rc` releases first until we're sure it's good to go.
