### ISSUE TITLE
Publish 0.7.5?

### ISSUE THREAD

**Issue by tfausak** [purescript-contrib/node-purescript-bin#12]
I see that 11478860a6a0aeea416c46c55c8043cd99ea97e1 updated to 0.7.5, but the latest version [on npm](https://www.npmjs.com/package/purescript) is 0.7.5-rc.2.

**Comment by garyb** [comment]
Yeah, until we're sure we're not going to release 0.7.5.x patches we hold off releasing a non-RC `npm` version, as otherwise the `npm` version falls out of sync with the `psc` version - 0.7.5.1 is not valid in semver.

I'm pretty sure there is a 0.7.5.1 to come too, is that right @paf31?

**Comment by paf31** [comment]
@garyb I think so. I haven't worked on anything yet, but there is a fix for the Haddock documentation, and I'll probably try to put fixes in this weekend for the two or three minor bugs which have come up.

**Comment by tfausak** [comment]
Now that [v0.7.5.2](https://github.com/purescript/purescript/releases/tag/v0.7.5.2) has been released, can this package be updated?

**Comment by garyb** [comment]
I think we're making a 0.7.5.3 too :smile: 

I did release a new `-rc.3` that is 0.7.5.1 though (which is functionally identical to 0.7.5.2).

**Comment by tfausak** [comment]
Works for me. Thanks!
