### ISSUE TITLE
Please don't release RCs as "latest"

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/node-purescript-bin#14]
See https://docs.npmjs.com/cli/publish

If you just `npm publish`, by default, it will use the `latest` tag. Anyone doing `npm install purescript` will get the `latest` tag by default. So right now, `npm install purescript` gets you 0.8.0-rc.1.

This probably isn't what we want for RC versions. Instead, for an RC version, we probably want the command to be `npm publish --tag next`. Then people can opt in to RCs by running `npm install purescript@next` if they want to, but plain `npm install purescript` will get you the latest proper release.

**Comment by garyb** [comment]
Interesting, that isn't what happens when I `npm i purescript`... I still get 0.7.6. According to `semver` a `-xxx` release should never be installed unless specifically asked for.

**Comment by shinnn** [comment]
With node v5.3.0 and npm v3.3.12 I got `0.7.6` too.

@hdgarrood Which version of npm are you using?

**Comment by hdgarrood** [comment]
Yeah, I think it's a bit weird that npm doesn't seem to follow semver here. Still, I did get the RC when I did it. Could it be because you already had purescript 0.7.6 in your node_modules directory?

**Comment by hdgarrood** [comment]
Not at my laptop right now but it was npm 3.

**Comment by shinnn** [comment]
> Could it be because you already had purescript 0.7.6 in your node_modules directory?

No...

Maybe we can check which installation result is the npm's default by creating a small repository and building it on a free CI (e.g. Travis CI).

@hdgarrood Also, which OS? (I'm using OS X 10.11.2.)

**Comment by hdgarrood** [comment]
Do either of you have package.json files which specify a version range for purescript?

**Comment by hdgarrood** [comment]
The npm documentation I linked seems pretty clear that what I described
is the intended behaviour, though. I'm on Ubuntu 14.04 but I don't think
that's relevant.

I'll have another look at this in a bit, when I'm at my laptop.

**Comment by garyb** [comment]
No, I was `npm i purescript`ing in a fresh directory, no `package.json` or anything.

**Comment by garyb** [comment]
Although OSX / node 0.12.2 / npm 2.7.4 does install the RC.

**Comment by shinnn** [comment]
https://github.com/purescript-contrib/node-purescript-bin/issues/14#issuecomment-166118300

> I'll have another look at this in a bit, when I'm at my laptop.

How was it?

**Comment by hdgarrood** [comment]
Ubuntu / node 4.2.3 / npm 3.5.2 installs 0.8.0-rc.1 in a fresh directory for me.

**Comment by hdgarrood** [comment]
As far as I can tell semver says nothing about installing prerelease versions, so I don't think npm is contravening it. I do think it's a bit odd that it doesn't at least warn when you publish a prerelease version as "latest" though.

I was just talking to someone in IRC who got bitten by this, btw.

To fix, see https://docs.npmjs.com/cli/dist-tag. AFAICT the fix should be:
```
$ npm dist-tag rm purescript latest
$ npm dist-tag add purescript@0.8.0-rc1 next
$ npm dist-tag add purescript@0.7.6 latest
```

**Comment by shinnn** [comment]
> Ubuntu / node 4.2.3 / npm 3.5.2 installs 0.8.0-rc.1 in a fresh directory for me.

Thanks for the report.

But, I still don't think we really should spend a time to add a dist-tag for each RC release. Currently we can install the stable version explicitly by running `npm install purescript@7`.

@hdgarrood Is there any *real* problem caused by unintentionally installed RC version?

============

FYI [babel-eslint](https://github.com/babel/babel-eslint) doesn't use dist-tag.

```
$ npm dist-tag ls babel-eslint
> latest: 5.0.0-beta6
```

**Comment by hdgarrood** [comment]
Yes - it's really confusing! Especially for newcomers, who get told to `npm install purescript` and then the rest of the documentation assumes they're on 0.7. And *especially* if they then write code that doesn't work in 0.7 when the rest of the purescript world is still on 0.7. The situation isn't so bad in this particular case, because 0.8 doesn't have any breaking changes, but it will be much worse if the same happens in 0.9, which will have breaking changes.

All I'm asking is that you run those above 3 commands, and then in the future, just make sure `latest` and `next` point to sensible versions.

Surely you would agree that the default behaviour should be to install a proper supported version, not a prerelease?

**Comment by shinnn** [comment]
OK, really convincing.

I added dist-tags to the package as you suggested:

```
$ npm dist-tag ls purescript
latest: 0.7.6
next: 0.8.0-rc1
```

Thanks again, @hdgarrood.

**Comment by hdgarrood** [comment]
Thank you! :)

**Comment by shinnn** [comment]
Um, not only me but also the collaborators should care about tagging. https://github.com/purescript-contrib/node-purescript-bin/commit/a074e4caeccd170cfcd5beae9b81c6953e933b41

```
$ npm dist-tag ls purescript
> latest: 0.8.1-rc.1
```

**Comment by garyb** [comment]
I was intending on releasing 0.8.1 proper about 5 minutes after I released that. When testing I discovered a pretty serious problem with 0.8.1 though (purescript/purescript#1905) so I got sidetracked.
