### ISSUE TITLE
NPM 3 issue

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/node-purescript-bin#15]
Report [here](https://twitter.com/toshok/status/692560089434169345)

**Comment by shinnn** [comment]
No enough information. At least I can correctly install `purescript` via npm 3.

```
$ node --version
v5.5.0
$ npm --version
3.5.3
$ npm i -g purescript
$ psc-bundle --version
0.7.6.1
$ psc-docs --version
0.7.6.1
$ psc-publish --version
0.7.6.1
$ psc --version
0.7.6.1
$ psci --version
0.7.6.1
```

Also, this is an npm issue. https://github.com/npm/npm/issues Thanks for the report though.

**Comment by garyb** [comment]
I've also been using npm 3 for a while without trouble, I suspect it's probably a local configuration issue.
