### ISSUE TITLE
Install fails on Node v6.0.0

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript-contrib/node-purescript-bin#19]
See https://travis-ci.org/paf31/purescript-yargs/builds/125931652

It appears the `--harmony_destructuring` flag is now obsolete.

**Comment by shinnn** [comment]
*Good* PR is always welcome.

**Comment by kRITZCREEK** [comment]
I'm not a node expert so I'm not quite sure what's the way forward here.

Node v4.* is the current LTS and we most definitely want to support that and Node v6.* is the newest version and I think we wan't to support that aswell.

So either we don't use object destructuring for now or ... there is some hidden node ninja way to use different flags for different versions.
