### ISSUE TITLE
Global installation fails because of ENOENT

### ISSUE THREAD

**Issue by passy** [purescript-contrib/node-purescript-bin#21]
Hi! Apologies that I can't look into this any further right now. I was trying to install this from master because I had just updated to Node 6 and got an error about unsupported flags when installing from npmjs.com.

```
npm install -g .
npm ERR! Linux 4.5.1-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "."
npm ERR! node v6.0.0
npm ERR! npm  v3.8.7
npm ERR! path /home/pascal/.node/lib/node_modules/purescript/bin/psc.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/pascal/.node/lib/node_modules/purescript/bin/psc.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/pascal/.node/lib/node_modules/purescript/bin/psc.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

Here's the full debug log: https://gist.github.com/passy/3a359aef435676b4cee6aa4684a38963

**Comment by shinnn** [comment]
Because `bin/psc.js` is generated by a [build script](https://github.com/purescript-contrib/node-purescript-bin/blob/f2bf2b3ce88366d27e13e35639ca018057b66638/build.js) and that's not included in this repository.

**Comment by shinnn** [comment]
Upgrade to 0.8.6-rc.1. Thanks.

**Comment by passy** [comment]
Ah, that makes sense. Thanks for the reply and fix!
