### ISSUE TITLE
node --harmony_destructuring error

### ISSUE THREAD

**Issue by fadjar340** [purescript-contrib/node-purescript-bin#22]
Dear Developer,

I have this issue..

npm ERR! purescript@0.8.5 postinstall: `node --harmony_destructuring lib/install.js`
npm ERR! Exit status 9
npm ERR!
npm ERR! Failed at the purescript@0.8.5 postinstall script 'node --harmony_destructuring lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony_destructuring lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purescript
npm ERR! There is likely additional logging output above.

I saw in the 
$node --v8-option | grep harmony
 --es_staging (enable test-worthy harmony features (for internal use only))
  --harmony (enable all completed harmony features)
  --harmony_shipping (enable all shipped harmony features)
  --harmony_object_observe (enable "harmony Object.observe" (in progress))
  --harmony_modules (enable "harmony modules" (in progress))
  --harmony_function_sent (enable "harmony function.sent" (in progress))
  --harmony_sharedarraybuffer (enable "harmony sharedarraybuffer" (in progress))
  --harmony_simd (enable "harmony simd" (in progress))
  --harmony_do_expressions (enable "harmony do-expressions" (in progress))
  --harmony_iterator_close (enable "harmony iterator finalization" (in progress))
  --harmony_tailcalls (enable "harmony tail calls" (in progress))
  --harmony_object_values_entries (enable "harmony Object.values / Object.entries" (in progress))
  --harmony_object_own_property_descriptors (enable "harmony Object.getOwnPropertyDescriptors()" (in progress))
  --harmony_regexp_property (enable "harmony unicode regexp property classes" (in progress))
  --harmony_function_name (enable "harmony Function name inference")
  --harmony_regexp_lookbehind (enable "harmony regexp lookbehind")
  --harmony_species (enable "harmony Symbol.species")
  --harmony_instanceof (enable "harmony instanceof support")
  --harmony_default_parameters (enable "harmony default parameters")
  --harmony_destructuring_assignment (enable "harmony destructuring assignment")
  --harmony_destructuring_bind (enable "harmony destructuring bind")
  --harmony_tostring (enable "harmony toString")
  --harmony_regexps (enable "harmony regular expression extensions")
  --harmony_unicode_regexps (enable "harmony unicode regexps")
  --harmony_sloppy (enable "harmony features in sloppy mode")
  --harmony_sloppy_let (enable "harmony let in sloppy mode")
  --harmony_sloppy_function (enable "harmony sloppy function block scoping")
  --harmony_proxies (enable "harmony proxies")
  --harmony_reflect (enable "harmony Reflect API")
  --harmony_regexp_subclass (enable "harmony regexp subclassing")

There are no   --harmony_destructuring 
Please check below
  --harmony_destructuring_assignment (enable "harmony destructuring assignment")
  --harmony_destructuring_bind (enable "harmony destructuring bind")

I think it will create error when I want to install

Regards,
Fadjar T

**Comment by shinnn** [comment]
https://github.com/purescript-contrib/node-purescript-bin/issues/19
