### ISSUE TITLE
Which version of node-purescript-bin responds to which purescript version?

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [purescript-contrib/node-purescript-bin#23]
I'm a bit lost I what version of this repo responds to which of purs.
Does psc --version return the version of the language?
Because for `purescript@0.8.5` version of this repo `psc --version` returned `0.8.4` and now after `npm i purescript@0.8.6-rc.1` and `psc --version` I get `0.8.5`. I must admit it's a bit confusing.

**Comment by damncabbage** [comment]
It's meant to be one-for-one (see https://github.com/purescript-contrib/node-purescript-bin/pull/20#issuecomment-216033979).
