### ISSUE TITLE
purescript.compile

### ISSUE THREAD

**Issue by askucher** [purescript-contrib/node-purescript-bin#29]
Can I do something like

```javascript
var purescript = require("purescript")
var js = purescript.compile("Code here")
console.log(js)
```

**Comment by shinnn** [comment]
Use [`child_process`](https://nodejs.org/api/child_process.html) module.

**Comment by askucher** [comment]
@shinnn You should not use child_process if you want to see your project alive.

**Comment by shinnn** [comment]
> You should not use child_process if you want to see your project alive. If you want to understand why please use StackOverflow

@askucher http://www.catb.org/esr/faqs/smart-questions.html#writewell
