### ISSUE TITLE
Cannot install on Arch

### ISSUE THREAD

**Issue by Pastafarianist** [purescript-contrib/node-purescript-bin#39]
When I run `npm install purescript@0.9.3`, after a while, it prints:

```
 > purescript@0.9.3 postinstall <long_path>/node_modules/purescript 
 > node lib/install.js 
   ⚠ The `<long_path>/node_modules/purescript/vendor/psc` binary doesn't seem to work correctly 
   ⚠ psc pre-build test failed 
   ℹ compiling from source
```

And it freezes. I waited about 2 hours and aborted the installation.

If I try to run the binary that "doesn't seem to work correctly" directly, without arguments, I get the following error:

    error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

I'm not sure how relevant that is.

If I try to install purescript from the repositories (I'm on Arch), it does not crash on launch.

**Comment by kRITZCREEK** [comment]
The prebuilt binaries have been linked against ncurses/libtinfo5 whereas Arch has version 6 of those. You can either install ncurses5-compat-libs from the AUR or build the compiler yourself, in which case GHC will link against your newer version of libtinfo, using whichever stack resolver was used for release 0.9.3.

**Comment by Pastafarianist** [comment]
Installing `ncurses5-compat-libs` fixed the problem for me. Thank you.
