### ISSUE TITLE
Update npm package to 0.11

### ISSUE THREAD

**Issue by i3games** [purescript-contrib/node-purescript-bin#42]
The package on npm is still at 0.10.7, which now breaks new installations, see e.g. [https://groups.google.com/forum/#!topic/purescript/HkOp7_zwqbU](https://groups.google.com/forum/#!topic/purescript/HkOp7_zwqbU)

**Comment by shinnn** [comment]
Duplicate of https://github.com/purescript-contrib/node-purescript-bin/issues/41
