### ISSUE TITLE
Include wrapper scripts (psc, etc.) in node_modules/.bin?

### ISSUE THREAD

**Issue by ethul** [purescript-contrib/node-purescript-bin#45]
I noticed that only `purs` is being included in `node_modules/.bin` with version `0.11.3`. I am wondering if it would it make sense to also include the wrapper scripts like `psc`, `psc-bundle`, etc.

They are present in `node_modules/purescript/vendor`.

**Comment by shinnn** [comment]
Read https://github.com/purescript-contrib/node-purescript-bin/pull/40#discussion_r108454191. Also wrapper scripts doesn't work on Windows.

**Comment by ethul** [comment]
Thanks for the link.
