### ISSUE TITLE
v0.7.0 install fail

### ISSUE THREAD

**Issue by e-jigsaw** [purescript-contrib/node-purescript-bin#5]
```
✈ npm i purescript
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/Cellar/nvm/0.23.3/versions/io.js/v2.3.3/bin/iojs" "/usr/local/opt/nvm/versions/io.js/v2.3.3/bin/npm" "i" "purescript"
npm ERR! node v2.3.3
npm ERR! npm  v2.11.3
npm ERR! path /Users/***/tmp/purs/node_modules/purescript/bin/psc.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/***/tmp/purs/node_modules/purescript/bin/psc.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/***/tmp/purs/npm-debug.log
```

`purescript@0.6.10` works

**Comment by e-jigsaw** [comment]
Maybe `postinstall` script should be `node lib/install.js && node build.js` ?

**Comment by shinnn** [comment]
Fixed and released v0.7.1. Thanks for reporting.

**Comment by e-jigsaw** [comment]
Great! I checked install successfully. Thanks

**Comment by shinnn** [comment]
Glad to hear that :)

**Comment by garyb** [comment]
That's... unfortunate. As now we have a version that is out of sync with the compiler again, which was confusing enough last time around, but there is going to be a "real" v0.7.1 this time, which will be even worse.

**Comment by shinnn** [comment]
> That's... unfortunate.

No. The really unfortunate thing is that this module doesn't follow semver. I think we should release this as v1.0.0.

**Comment by shinnn** [comment]
[elm-bin](https://github.com/kevva/elm-bin) is a good example for this case. Currently it wraps [elm v0.15.1](https://github.com/kevva/elm-bin/commit/f097e6d52c88e9f67b7a03330a180181b5da5642) but it's package version is [v2.0.0](https://github.com/kevva/elm-bin/blob/49956ef07df901da79ba9a401499b6290d8dfa20/package.json#L3).

**Comment by garyb** [comment]
Yeah, that makes sense. I wish we'd gone with `purescript-bin` or something like that instead, as I think naming it just `purescript` is what makes the mismatching versions a bit odd.

**Comment by e-jigsaw** [comment]
+1 `purescript-bin`

**Comment by shinnn** [comment]
OK, regardless of `purescript-bin` idea, I'll unpublish current v0.7.0 and v0.7.1, then publish v0.7.0-0 instead. It more matches the current PureScript version (v0.7.0**.0**).

What do you think?

**Comment by garyb** [comment]
Would that cause problems with npm treating it as a pre-release? I think it treats `v0.7.0-0` as `< v0.7.0`.

I don't know what to do anymore :smile:
