### ISSUE TITLE
installation failed Failed at the purescript@0.11.6 postinstall script 'node lib/install.js'.

### ISSUE THREAD

**Issue by RaviTejaKomma** [purescript-contrib/node-purescript-bin#52]
I am getting an error when I try to install using **npm install -g purescript** command. The log of the error is 
 `
>purescript@0.11.6 postinstall C:\Users\RAVI TEJA\AppData\Roaming\npm\node_modules\purescript
> node lib/install.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "purescript"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! purescript@0.11.6 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the purescript@0.11.6 postinstall script 'node lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purescript
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log`

npm version : 3.10.9
node version : 6.9.2

**Comment by shinnn** [comment]
In the first place Node.js 6.9.2 is a very old version of the LTS "Boron" line and misses [an important security update](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/).

Update Node.js to the latest version of 6.x or 8.x, and check if `npm install -g purescript` still fails.
