### ISSUE TITLE
0.7.3 version broken

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/node-purescript-bin#9]
I somehow managed to publish `0.7.3` without the `bin` folder, so this version is broken. At least `0.7.3` won't even install, it's treated as an error when attempting to do so.

I've republished it as `0.7.3-fixed` and added a notice using `npm deprecate` to tell people to use the other version... but :sob:. A pretty poor solution since `npm install purescript` picks up `0.7.3` by default now.

**Comment by garyb** [comment]
Actually I've unpublish the `0.7.3` version entirely, the fact that `npm install purescript` was broken means it's probably better to do that for now. Hopefully `0.7.4` won't be too long in coming...

**Comment by seanstrom** [comment]
Thanks @garyb! Publishing to NPM has been tricky for me in the past as well aha.
In any case, since we have `0.7.4` can we close this?
Not being trying to be bossy, I was just wanting to clean up the issues :).

**Comment by garyb** [comment]
Yep! Thanks for the reminder :smile:.
